Repository agamjotsingh18/codesetgo, pull requests merged in 2023-06, with the labels that each got.

#323 Added CodeQL workflow
  .github/workflows/codeql.yml
Labels: Easy

#327 Added styling to whole UI including many details under issue #311
  assets/css/darkmode.css
  assets/css/style.css
  assets/js/main.js
  index.html
Labels: Level2, GSSOC23

#352 centered the image of about section
  assets/css/style.css
Labels: Easy, Level1, GSSOC23

#367 new footer changes to hacktober.html file
  hacktoberfest.html
Labels: Easy, Level1, GSSOC23

#404 Designed and coded a footer as specified by the project maintainers.
  assets/css/style.css
  index.html
Labels: Level1, GSSOC23

#418 Added JS Validation on contact form to enhance UI issue#403 resolved
  assets/css/enquiry-form.css
  assets/js/main.js
  index.html
Labels: Easy, Level1, GSSOC23

#420 Preloader added
  assets/img/Rhombus.gif
  assets/js/darkmode_logic.js
  assets/js/hacktoberfest.js
  assets/js/main.js
  hacktoberfest.html
  index.html
Labels: Easy, Level1, GSSOC23

#477 cheatsheet-update
  assets/css/style.css
  cheatsheets.html
Labels: Level2, GSSOC23
